### ISSUE TITLE
New extract doesn't have Unit to GPS car id table

### ISSUE THREAD

**Issue by danielgavrilov** [ucl-team-8/service#21]
We had a **Unit to GPS car id** table in the East Coast extract, but in the new one we don't. The units in the new one are gps_car_ids themselves and there is no need to lookup anything.

So we have 2 options:
1. Make a Unit to GPS car id table for the new extract that simply maps a value to itself
2. Remove the Unit to GPS car id mapping table from the database, and in the old data, replace the units with gps_car_ids

Option 1 is easier, but option 2 is better, since there's less queries to database. How hard would it be to do 2?

**Comment by AxelGoetz** [comment]
For the algorithm option 2 shouldn't be too hard because the only time we use unit is when we check the genius allocations.

**Comment by danielgavrilov** [comment]
@AxelGoetz the new extract also doesn't have CIF_UID in the genius allocations, is that fine?

**Comment by AxelGoetz** [comment]
I will have to change the code slightly but since we are not using it anywhere, it shouldn't be a problem.

**Comment by danielgavrilov** [comment]
@AxelGoetz Should we rename the `Schedule` model to use `gps_car_id` rather than `unit` field? How messy can it get?

**Comment by AxelGoetz** [comment]
@danielgavrilov it always gets messy but it might be better in the long run.

**Comment by danielgavrilov** [comment]
@AxelGoetz What long run are you talking about?
