### ISSUE TITLE
SDK/collaboration opportunities for further development

### ISSUE THREAD

**Issue by danielgavrilov** [ucl-team-8/service#41]

**Comment by AxelGoetz** [comment]
I have already started writing this so I'll finish it. But @danielgavrilov, you will have to give me some bullet points with what you want to do if you had more time.

**Comment by danielgavrilov** [comment]
@AxelGoetz is there a Google Doc?

**Comment by AxelGoetz** [comment]
@danielgavrilov there is, in the website folder.
