### ISSUE TITLE
Technical achievements, implementation details, use of design patterns

### ISSUE THREAD

**Issue by danielgavrilov** [ucl-team-8/service#45]

**Comment by AxelGoetz** [comment]
Do we want to include the first algorithm or just talk about algorithm2?

**Comment by danielgavrilov** [comment]
I think we should mention first algorithm too, not go into much depth but in general:
- What was the idea (live segments?)
- How it performed
- What problems it had

Though if these things are mentioned in another section, that's fine, as long as we mention them somewhere.
